version: '2'

services:

  postgres:
    build: ./postgres
    volumes:
      - "/opt/teamcity/pg_data:/var/lib/postgresql/data"
      - "/opt/teamcity/pg_backup:/backups"
    env_file: .env
    restart: always

  mysql:
     image: mysql:5.7
     container_name: mysql57
     ports:
      - 3307:3306
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "root"
     volumes:
      - ./scripts/docker/mysql/:/docker-entrypoint-initdb.d/

  server:
    image: jetbrains/teamcity-server:latest
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    ports:
      - 8111:8111
    depends_on:
      - postgres
    env_file: .env
    restart: always

  agent:
    build: ./agents/sonar-scanner
    env_file: .env
    restart: always

  agent2:
    build: ./agents/msbuild-net-core-sonar-scanner
    env_file: .env
    depends_on:
      - mysql
    restart: always
